export const styles = {
  page: { display: "flex", background: "#0d0d0d", minHeight: "100vh", color: "#e8dcc8", fontFamily: "'Cormorant Garamond', serif" },
  sidebar: { 
    width: "220px", 
    borderRight: "1px solid #1e1a16", 
    display: "flex", 
    flexDirection: "column",
    justifyContent: "space-between",
    padding: "10px 0", 
    position: "fixed",
    top: 0, 
    left: 0, 
    height: "100vh", 
    flexShrink: 0, 
    background: "#0d0d0d", 
    zIndex: 50,
  },
  sidebarLogo: { fontSize: "18px", fontWeight: 600, letterSpacing: "4px", padding: "16px 24px 4px" },
  sidebarSub: { fontFamily: "'Jost',sans-serif", fontSize: "10px", letterSpacing: "3px", color: "#4a3f32", padding: "0 24px", margin: "0 0 8px", textTransform: "uppercase" },
  sidebarNav: { display: "flex", flexDirection: "column", gap: "2px" },
  sidebarBtn: { background: "none", border: "none", borderLeft: "2px solid transparent", color: "#6a5f52", cursor: "pointer", padding: "12px 24px", textAlign: "left", fontFamily: "'Jost',sans-serif", fontSize: "13px", letterSpacing: "1px" },
  sidebarActive: { color: "#c9a96e", background: "rgba(201,169,110,0.08)", borderLeft: "2px solid #c9a96e" },
  sidebarFooter: { padding: "24px" },
  backBtn: { background: "rgba(201,169,110,0.07)", border: "1px solid rgba(201,169,110,0.2)", color: "#a09080", cursor: "pointer", fontFamily: "'Jost',sans-serif", fontSize: "12px", letterSpacing: "1px", padding: "7px 14px", width: "100%", textAlign: "left" },
  logoutBtn: { background: "rgba(201,123,110,0.08)", border: "1px solid rgba(201,123,110,0.25)", color: "#c97b6e", cursor: "pointer", fontFamily: "'Jost',sans-serif", fontSize: "11px", letterSpacing: "1px", padding: "7px 14px", marginTop: "12px", width: "100%", textAlign: "left" },
  main: { flex: 1, padding: "48px 60px", overflowY: "auto", marginLeft: "220px" },
  pageTitle: { fontSize: "42px", fontWeight: 300, margin: "0 0 40px" },
  tabHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "32px" },
  statsGrid: { display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: "16px", marginBottom: "60px" },
  statCard: { border: "1px solid #1e1a16", padding: "28px", display: "flex", flexDirection: "column", gap: "8px" },
  statIcon: { fontSize: "20px" },
  statValue: { fontSize: "32px", fontWeight: 300 },
  statLabel: { fontFamily: "'Jost',sans-serif", fontSize: "10px", letterSpacing: "2px", color: "#4a3f32", textTransform: "uppercase" },
  sectionTitle: { fontSize: "28px", fontWeight: 300, margin: "0 0 24px" },
  tableWrap: { border: "1px solid #1e1a16", overflow: "hidden" },
  table: { width: "100%", borderCollapse: "collapse" },
  th: { fontFamily: "'Jost',sans-serif", fontSize: "10px", letterSpacing: "2px", color: "#4a3f32", textTransform: "uppercase", padding: "14px 20px", textAlign: "left", borderBottom: "1px solid #1e1a16", background: "#111" },
  tr: { borderBottom: "1px solid #1a1612" },
  td: { padding: "14px 20px", fontFamily: "'Jost',sans-serif", fontSize: "13px", color: "#8a7a68", verticalAlign: "middle" },
  addBtn: { background: "#c9a96e", border: "none", color: "#0d0d0d", padding: "12px 28px", fontFamily: "'Jost',sans-serif", fontSize: "11px", letterSpacing: "2px", cursor: "pointer", fontWeight: 500, textTransform: "uppercase" },
  editBtn: { background: "none", border: "1px solid #2a2520", color: "#8a7a68", padding: "6px 14px", cursor: "pointer", fontFamily: "'Jost',sans-serif", fontSize: "11px", marginRight: "8px" },
  delBtn: { background: "none", border: "1px solid #3a1a16", color: "#c97b6e", padding: "6px 14px", cursor: "pointer", fontFamily: "'Jost',sans-serif", fontSize: "11px" },
  overlay: { position: "fixed", inset: 0, background: "rgba(0,0,0,0.8)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 999 },
  modal: { background: "#111", border: "1px solid #2a2520", width: "440px", maxHeight: "80vh", overflow: "auto" },
  modalHead: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "24px 32px", borderBottom: "1px solid #1e1a16" },
  modalTitle: { fontSize: "22px", fontWeight: 400, margin: 0 },
  closeBtn: { background: "none", border: "none", color: "#6a5f52", cursor: "pointer", fontSize: "16px" },
  modalBody: { padding: "24px 32px", display: "flex", flexDirection: "column", gap: "16px" },
  field: {},
  fieldLabel: { display: "block", fontFamily: "'Jost',sans-serif", fontSize: "10px", letterSpacing: "2px", color: "#6a5f52", textTransform: "uppercase", marginBottom: "8px" },
  input: { width: "100%", background: "#0d0d0d", border: "1px solid #2a2520", color: "#e8dcc8", padding: "10px 14px", fontFamily: "'Jost',sans-serif", fontSize: "14px", boxSizing: "border-box", outline: "none" },
  saveBtn: { background: "#c9a96e", border: "none", color: "#0d0d0d", padding: "12px", fontFamily: "'Jost',sans-serif", fontSize: "12px", letterSpacing: "2px", cursor: "pointer", fontWeight: 500, textTransform: "uppercase", marginTop: "8px" },
};